import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {evaluate} from '../core.js';
import {pageCommand} from '../page.js';
const require=createRequire(import.meta.url);
const {JSDOM}=require(process.env.JEV_TEST_DEPS || 'jsdom');
const html=await readFile(new URL('../popup.html',import.meta.url),'utf8');
const script=(await readFile(new URL('../popup.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
const waitFor=async condition=>{for(let i=0;i<200;i++){if(condition()) return;await new Promise(r=>setTimeout(r,10));}throw new Error('UI did not settle');};
function popup({evaluateFn=evaluate,call=async()=>({answers:{}}),pageFn=()=>({token:'t',fields:[{id:'f0',kind:'checkbox',label:'Active'}]})}={}) {
  const dom=new JSDOM(html,{url:'https://extension.test/popup.html',runScripts:'outside-only'});
  const win=dom.window;
  let saved={};
  win.evaluate=evaluateFn;win.pageCommand=pageCommand;win.callJev=call;win.AbortController=AbortController;
  win.chrome={storage:{local:{setAccessLevel:async()=>{},get:async()=>saved,set:async x=>{saved={...saved,...x};},remove:async()=>{saved={};}}},tabs:{query:async()=>[{id:1,url:'https://example.com/form'}]},scripting:{executeScript:async x=>[{result:await pageFn(x.args[0])}]}};
  win.eval(script);
  return {dom,win,$:id=>win.document.getElementById(id),saved:()=>saved};
}
test('editing source during an in-flight analysis cannot revive stale candidates', async()=>{
  let complete;
  const ui=popup({evaluateFn:()=>new Promise(resolve=>{complete=resolve;})});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='test-key';ui.$('source').value='Name: Alice';ui.$('analyze').click();
  await waitFor(()=>complete);
  assert.equal(ui.$('source').readOnly,true);
  ui.$('source').value='Name: Bob';ui.$('source').dispatchEvent(new ui.win.Event('input'));
  complete([{id:'f0',field:{label:'Name'},status:'ready',value:'Alice'}]);
  await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('apply').disabled,true);
  assert.equal(ui.$('results').hidden,true);
  assert.match(ui.$('status').textContent,/文章が変わ/);
});
test('full popup-to-form flow uses real planner and page adapter, supports OFF and undo without submission', async()=>{
  const form=new JSDOM(`<form><h2>Webhook</h2><label><input id=active type=checkbox checked>Active</label><button type=submit>Submit</button></form>`,{url:'https://example.com/form',runScripts:'outside-only'});
  form.window.HTMLElement.prototype.getClientRects=function(){return [{width:10,height:10}];};
  const page=form.window.eval(`(${pageCommand.toString()})`);
  let submissions=0;form.window.document.querySelector('form').addEventListener('submit',()=>submissions++);
  const ui=popup({pageFn:page,call:async body=>({answers:Object.fromEntries(Object.entries(body.questions).map(([id,q])=>[id,q.type==='noul'?{type:'noul',noul:0.99}:{type:'choice',choice:'off',confidence:0.99,probabilities:{skip:0.005,on:0.005,off:0.99}}]))})});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='test-key';ui.$('source').value='Webhook: Active のチェックを外す';ui.$('analyze').click();
  await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('apply').disabled,false);
  assert.equal(ui.$('count').textContent,'1件の候補 / 1項目');
  const diagnostics=JSON.parse(ui.$('diagnostics').value);
  assert.equal(diagnostics.rows[0].diagnostics.at(-1).stage,'verification');
  assert.equal(diagnostics.rows[0].diagnostics.at(-1).accepted,true);
  assert.equal(ui.$('diagnostics').value.includes('test-key'),false);
  ui.$('apply').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(form.window.document.querySelector('#active').checked,false);
  assert.equal(ui.$('apply').disabled,true);
  assert.match(ui.$('status').textContent,/1件を入力/);
  ui.$('undo').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(form.window.document.querySelector('#active').checked,true);
  assert.equal(submissions,0);
});
test('a failed API request leaves the form untouched and no apply plan; keys are stored only on explicit save',async()=>{
  let applies=0;
  const ui=popup({call:async()=>{throw new Error('quota');},pageFn:request=>{if(request.op==='apply') applies++;return {token:'t',fields:[{id:'f0',kind:'checkbox',label:'Active'}]};}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='test-key';ui.$('source').value='Active: off';ui.$('analyze').click();
  await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/quota/);assert.equal(ui.$('apply').disabled,true);assert.equal(applies,0);assert.deepEqual(ui.saved(),{});
  ui.$('remember').checked=true;ui.$('save-key').click();await waitFor(()=>!ui.$('save-key').disabled);
  assert.equal(ui.saved().apiKey,'test-key');
  ui.$('forget-key').click();await waitFor(()=>!ui.$('forget-key').disabled);
  assert.deepEqual(ui.saved(),{});
});
