import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {evaluate} from '../core.js';
import {pageCommand} from '../page.js';
import {resolveLanguage,translator,localizeMessage} from '../i18n.js';
import {providers,providerOf,validAccountId,DEFAULT_PROVIDER} from '../providers.js';
const require=createRequire(import.meta.url);
const {JSDOM}=require(process.env.JEV_TEST_DEPS || 'jsdom');
const html=await readFile(new URL('../popup.html',import.meta.url),'utf8');
const script=(await readFile(new URL('../popup.js',import.meta.url),'utf8')).replace(/^import .*;\n/gm,'');
const waitFor=async condition=>{for(let i=0;i<200;i++){if(condition()) return;await new Promise(r=>setTimeout(r,10));}throw new Error('UI did not settle');};
function popup({evaluateFn=evaluate,call=async()=>({answers:{}}),pageFn=()=>({token:'t',fields:[{id:'f0',kind:'checkbox',label:'Active'}]}),uiLanguage='ja',initialSaved={}}={}) {
  const dom=new JSDOM(html,{url:'https://extension.test/popup.html',runScripts:'outside-only'});
  const win=dom.window;
  let saved={...initialSaved};
  win.evaluate=evaluateFn;win.pageCommand=pageCommand;win.callJev=call;win.AbortController=AbortController;
  win.resolveLanguage=resolveLanguage;win.translator=translator;win.localizeMessage=localizeMessage;win.providers=providers;win.providerOf=providerOf;win.validAccountId=validAccountId;win.DEFAULT_PROVIDER=DEFAULT_PROVIDER;
  win.chrome={i18n:{getUILanguage:()=>uiLanguage},storage:{local:{setAccessLevel:async()=>{},get:async()=>saved,set:async x=>{saved={...saved,...x};},remove:async key=>{delete saved[key];}}},tabs:{query:async()=>[{id:1,url:'https://example.com/form'}]},scripting:{executeScript:async x=>[{result:await pageFn(x.args[0])}]}};
  win.eval(script);
  return {dom,win,$:id=>win.document.getElementById(id),saved:()=>saved};
}
test('editing source during an in-flight analysis cannot revive stale candidates', async()=>{
  let complete;
  const ui=popup({evaluateFn:()=>new Promise(resolve=>{complete=resolve;})});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='test-key';ui.$('source').value='Name: Alice';ui.$('analyze').click();
  await waitFor(()=>complete);
  assert.equal(ui.$('source').readOnly,true);
  ui.$('source').value='Name: Bob';ui.$('source').dispatchEvent(new ui.win.Event('input'));
  complete([{id:'f0',field:{label:'Name'},status:'ready',value:'Alice'}]);
  await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('apply').disabled,true);
  assert.equal(ui.$('results').hidden,true);
  assert.match(ui.$('status').textContent,/文章が変わ/);
});
test('English popup localizes controls, API errors and apply failures',async()=>{
  const ui=popup({uiLanguage:'en-US',evaluateFn:async()=>[{id:'f0',field:{label:'Active',kind:'checkbox'},status:'ready',value:false,display:'オフ',reason:'元の文章に一致する候補です。'}],pageFn:request=>request.op==='apply'?[{id:'f0',status:'failed',reason:'入力後にページが値を変更しました。'}]:{token:'t',fields:[{id:'f0',kind:'checkbox',label:'Active'}]}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  assert.equal(ui.win.document.documentElement.lang,'en');
  assert.equal(ui.$('target').textContent,'Target · example.com/form');
  assert.equal(ui.$('analyze').textContent,'Create proposals with TypeSafe');
  ui.$('source').value='Active: off';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/Set your TypeSafe API key/);
  ui.$('api-key').value='test-key';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('count').textContent,'1 proposals / 1 fields');
  assert.match(ui.$('rows').textContent,/Off/);
  ui.$('apply').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/Could not set: 1/);
  assert.match(ui.$('rows').textContent,/The page changed the value after filling/);
});

test('switching language preserves source values, unchecked proposals and API key preferences',async()=>{
  const candidates=[{id:'f0',field:{label:'氏名',kind:'text'},status:'ready',value:'新井 美香',display:'新井 美香',reason:'元の文章に一致する候補です。'},{id:'f1',field:{label:'Active',kind:'checkbox'},status:'ready',value:false,display:'オフ',reason:'元の文章に一致する候補です。'}];
  const ui=popup({uiLanguage:'en',initialSaved:{apiKey:'saved-key'},evaluateFn:async()=>structuredClone(candidates),pageFn:()=>({token:'t',fields:[{id:'f0',kind:'text',label:'氏名'}],unsupported:true})});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('source').value='氏名: 新井 美香';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  ui.win.document.querySelector('[data-field-id=f0]').checked=false;
  ui.$('language').value='ja';ui.$('language').dispatchEvent(new ui.win.Event('change'));await waitFor(()=>ui.$('analyze').textContent==='TypeSafeへ送って候補を作る');
  assert.equal(ui.$('source').value,'氏名: 新井 美香');
  assert.equal(ui.$('target').textContent,'入力先 · example.com/form');
  assert.equal(ui.$('status').textContent,'候補を作成しました。確認後に入力してください。 独自の選択UIやiframeは対象外になる場合があります。');
  assert.equal(ui.win.document.querySelector('[data-field-id=f0]').checked,false);
  assert.match(ui.$('rows').textContent,/新井 美香/);
  assert.equal(ui.saved().keys.typesafe,'saved-key');assert.equal(ui.saved().uiLanguage,'ja');
  ui.$('forget-key').click();await waitFor(()=>!ui.$('forget-key').disabled);
  assert.deepEqual(ui.saved(),{uiLanguage:'ja'});
});
test('full popup-to-form flow uses real planner and page adapter, supports OFF and undo without submission', async()=>{
  const form=new JSDOM(`<form><h2>Webhook</h2><label><input id=active type=checkbox checked>Active</label><button type=submit>Submit</button></form>`,{url:'https://example.com/form',runScripts:'outside-only'});
  form.window.HTMLElement.prototype.getClientRects=function(){return [{width:10,height:10}];};
  const page=form.window.eval(`(${pageCommand.toString()})`);
  let submissions=0;form.window.document.querySelector('form').addEventListener('submit',()=>submissions++);
  const ui=popup({pageFn:page,call:async body=>({answers:Object.fromEntries(Object.entries(body.questions).map(([id,q])=>[id,q.type==='noul'?{type:'noul',noul:0.99}:{type:'choice',choice:'off',confidence:0.99,probabilities:{skip:0.005,on:0.005,off:0.99}}]))})});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='test-key';ui.$('source').value='Webhook: Active のチェックを外す';ui.$('analyze').click();
  await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('apply').disabled,false);
  assert.equal(ui.$('count').textContent,'1件の候補 / 1項目');
  const diagnostics=JSON.parse(ui.$('diagnostics').value);
  assert.equal(diagnostics.rows[0].diagnostics.at(-1).stage,'verification');
  assert.equal(diagnostics.rows[0].diagnostics.at(-1).accepted,true);
  assert.equal(ui.$('diagnostics').value.includes('test-key'),false);
  ui.$('apply').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(form.window.document.querySelector('#active').checked,false);
  assert.equal(ui.$('apply').disabled,true);
  assert.match(ui.$('status').textContent,/1件を入力/);
  ui.$('undo').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(form.window.document.querySelector('#active').checked,true);
  assert.equal(submissions,0);
});
test('a failed API request leaves the form untouched and no apply plan; keys are stored only on explicit save',async()=>{
  let applies=0;
  const ui=popup({call:async()=>{throw new Error('quota');},pageFn:request=>{if(request.op==='apply') applies++;return {token:'t',fields:[{id:'f0',kind:'checkbox',label:'Active'}]};}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='test-key';ui.$('source').value='Active: off';ui.$('analyze').click();
  await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/quota/);assert.equal(ui.$('apply').disabled,true);assert.equal(applies,0);assert.deepEqual(ui.saved(),{});
  ui.$('remember').checked=true;ui.$('save-key').click();await waitFor(()=>!ui.$('save-key').disabled);
  assert.equal(ui.saved().keys.typesafe,'test-key');
  ui.$('forget-key').click();await waitFor(()=>!ui.$('forget-key').disabled);
  assert.deepEqual(ui.saved(),{});
});
const plain=x=>JSON.parse(JSON.stringify(x));
const cfAccount='0123456789abcdef0123456789abcdef';
const choose=async(ui,id)=>{ui.$('provider').value=id;ui.$('provider').dispatchEvent(new ui.win.Event('change'));await waitFor(()=>!ui.$('provider').disabled);};
test('a legacy apiKey migrates to keys.typesafe and the old entry is removed',async()=>{
  const ui=popup({initialSaved:{apiKey:'legacy-key',uiLanguage:'ja'}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  assert.deepEqual(plain(ui.saved()),{keys:{typesafe:'legacy-key'},uiLanguage:'ja'});
  assert.equal(ui.$('provider').value,'typesafe');assert.equal(ui.$('api-key').value,'legacy-key');assert.equal(ui.$('remember').checked,true);
});
test('each provider sends only its own key; deleting a key affects only the selected provider',async()=>{
  const calls=[];let options;
  const ui=popup({initialSaved:{keys:{typesafe:'ts-key',cloudflare:'cf-token'},provider:'cloudflare',accountId:cfAccount},evaluateFn:async(source,fields,request,progress,opts)=>{options=opts;await request({model:'x'});return [];},call:async(body,key,opts)=>{calls.push({key,provider:opts.provider.id,accountId:opts.accountId});return {answers:{}};}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  assert.equal(ui.$('provider').value,'cloudflare');assert.equal(ui.$('account-field').hidden,false);assert.equal(ui.$('api-key').value,'cf-token');
  assert.equal(ui.$('analyze').textContent,'Cloudflare Workers AIへ送って候補を作る');
  ui.$('source').value='Active: off';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.deepEqual(calls,[{key:'cf-token',provider:'cloudflare',accountId:cfAccount}]);
  assert.equal(options.model,'clef-flash');assert.equal(options.thresholds,providers.cloudflare.thresholds);
  const diagnostics=JSON.parse(ui.$('diagnostics').value);
  assert.equal(diagnostics.provider,'cloudflare');assert.deepEqual(diagnostics.thresholds,{...providers.cloudflare.thresholds});
  assert.equal(ui.$('diagnostics').value.includes('cf-token')||ui.$('diagnostics').value.includes('ts-key'),false);
  ui.$('forget-key').click();await waitFor(()=>!ui.$('forget-key').disabled);
  assert.deepEqual(plain(ui.saved().keys),{typesafe:'ts-key'});
  await choose(ui,'typesafe');
  assert.equal(ui.$('account-field').hidden,true);assert.equal(ui.$('api-key').value,'ts-key');assert.equal(ui.saved().provider,'typesafe');
  ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.deepEqual(calls.at(-1),{key:'ts-key',provider:'typesafe',accountId:cfAccount});
});
test('switching provider discards proposals made with the previous provider',async()=>{
  const ui=popup({evaluateFn:async()=>[{id:'f0',field:{label:'Active',kind:'checkbox'},status:'ready',value:false,display:'オフ',reason:'元の文章に一致する候補です。'}]});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('api-key').value='ts-key';ui.$('source').value='Active: off';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('apply').disabled,false);assert.equal(ui.$('results').hidden,false);
  await choose(ui,'cloudflare');
  assert.equal(ui.$('apply').disabled,true);assert.equal(ui.$('results').hidden,true);assert.equal(ui.$('diagnostics').value,'');
  assert.equal(ui.$('api-key').value,'');
});
test('cloudflare needs a token and a 32-character account id; saved keys of either provider are kept out of the text',async()=>{
  let calls=0;
  const ui=popup({initialSaved:{keys:{typesafe:'ts-secret-key'}},call:async()=>{calls++;return {answers:{}};}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  await choose(ui,'cloudflare');
  ui.$('source').value='Active: off';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/APIトークンを設定/);
  ui.$('api-key').value='cf-token';ui.$('account-id').value='not-an-id';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/Account ID/);
  ui.$('account-id').value=cfAccount;ui.$('source').value='Active: off ts-secret-key';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.match(ui.$('status').textContent,/保存済みのAPIキー・トークンが含まれ/);
  assert.equal(calls,0);
  ui.$('remember').checked=true;ui.$('save-key').click();await waitFor(()=>!ui.$('save-key').disabled);
  assert.deepEqual(plain(ui.saved().keys),{typesafe:'ts-secret-key',cloudflare:'cf-token'});assert.equal(ui.saved().accountId,cfAccount);
});
test('editing the account id discards proposals; deleting the cloudflare token also deletes the saved account id',async()=>{
  const ui=popup({initialSaved:{keys:{cloudflare:'cf-token'},provider:'cloudflare',accountId:cfAccount},evaluateFn:async()=>[{id:'f0',field:{label:'Active',kind:'checkbox'},status:'ready',value:false,display:'オフ',reason:'元の文章に一致する候補です。'}]});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.$('source').value='Active: off';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.equal(ui.$('apply').disabled,false);
  ui.$('account-id').value='ffffffffffffffffffffffffffffffff';ui.$('account-id').dispatchEvent(new ui.win.Event('input'));
  assert.equal(ui.$('apply').disabled,true);assert.equal(ui.$('results').hidden,true);
  ui.$('remember').checked=false;ui.$('save-key').click();await waitFor(()=>!ui.$('save-key').disabled);
  assert.equal(ui.saved().keys,undefined);assert.equal(ui.saved().accountId,undefined);
  ui.$('api-key').value='cf-token';ui.$('remember').checked=true;ui.$('save-key').click();await waitFor(()=>!ui.$('save-key').disabled);
  assert.equal(ui.saved().accountId,'ffffffffffffffffffffffffffffffff');
  ui.$('forget-key').click();await waitFor(()=>!ui.$('forget-key').disabled);
  assert.deepEqual(plain(ui.saved()),{provider:'cloudflare'});
});
test('a storage failure while switching provider still swaps the key field, so the old key is never sent to the new host',async()=>{
  const calls=[];
  const ui=popup({initialSaved:{keys:{typesafe:'ts-key'},accountId:cfAccount},evaluateFn:async(source,fields,request)=>{await request({});return [];},call:async(body,key,opts)=>{calls.push([key,opts.provider.id]);return {answers:{}};}});
  await waitFor(()=>ui.$('target').textContent.includes('example.com'));
  ui.win.chrome.storage.local.set=async()=>{throw new Error('quota');};
  await choose(ui,'cloudflare');
  assert.equal(ui.$('api-key').value,'');
  ui.$('source').value='Active: off';ui.$('analyze').click();await waitFor(()=>!ui.$('analyze').disabled);
  assert.deepEqual(calls,[]);assert.match(ui.$('status').textContent,/APIトークンを設定/);
});
